name: test-suite

on:
  push:
    branches:
      - main
      - 'pr/*'
  pull_request:
env:
  # Deny warnings in CI
  RUSTFLAGS: "-D warnings"
jobs:
  cargo-fmt:
    name: cargo-fmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: arduino/setup-protoc@e52d9eb8f7b63115df1ac544a1376fdbf5a39612
    - name: Get latest version of stable Rust
      run: rustup update stable
    - name: Check formatting with cargo fmt
      run: cargo fmt --all -- --check
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: arduino/setup-protoc@e52d9eb8f7b63115df1ac544a1376fdbf5a39612
    - name: Get latest version of stable Rust
      run: rustup update stable
    - name: Check style with clippy
      run: cargo clippy --tests --all
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: test-${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: arduino/setup-protoc@e52d9eb8f7b63115df1ac544a1376fdbf5a39612
    - name: Get latest version of stable Rust
      run: rustup update stable
    - name: Run tests
      run: cargo test --release
    - name: Check all examples, binaries, etc
      run: cargo check --all-targets
